# API Configuration
api:
  host: "0.0.0.0"
  port: 8000

# Extractor Configuration
extractors:
  text:
    chunk_size: 1000
    chunk_overlap: 200
  table:
    enabled: true
  image:
    enabled: true
    min_size: 100  # Minimum size in pixels to consider

# Embedder Configuration
embedders:
  text:
    model: "all-MiniLM-L6-v2"
    dimension: 384
  table:
    model: "all-MiniLM-L6-v2"
    dimension: 384
  image:
    model: "clip-ViT-B-32"
    dimension: 512

# Vector Store Configuration
vector_store:
  collection_prefix: "rag_"
  similarity_threshold: 0.7
